CREATE TABLE tai_entry_his(
	balance_water_no char(18) NOT NULL,
	card_main_code char(14) NOT NULL,
	card_status_id char(2) NOT NULL,
	card_sub_code char(2) NOT NULL,
	device_id char(4) NULL,
	device_type_id char(2) NULL,
	in_time date NULL,
	line_id char(2) NOT NULL,
	sam_logical_id char(16) NOT NULL,
	sam_tr_seq integer NOT NULL,
	station_id char(2) NOT NULL,
	tk_balance decimal(12,2) NOT NULL,
	tk_logic_no char(16) NOT NULL,
	tk_phy_no char(20) NOT NULL,
	squad_date integer NOT NULL,
	time_section char(4) NOT NULL,
	id numeric(16,0) NULL,
	counter_time char(4) NULL,
	bus_times_counter integer NULL,
	metro_times_counter integer NULL,
	union_times_counter integer NULL,
	tk_charge_cnt integer NULL,
	tk_deal_cnt integer NULL,
	tac char(10) NULL,
	paymode_id char(2) NULL,
	last_sam_logical_id char(16) NULL,
	last_deal_time char(19) NULL,
	tr_sort char(2) NULL,
	area_code char(4) NULL,
	area_tk_type char(4) NULL,
	overdraft integer NULL,
	cpu_tk char(1) NULL,
	expired_tk char(1) NULL,
	tct_valid_days integer NULL,
	tct_activate_time date NULL,
	limit_mode char(3) NULL,
	limit_entry_station char(4) NULL,
	limit_exit_station char(4) NULL,
	data_file_name varchar2(42) NULL,
	file_name varchar2(42) NULL);