load data
CHARACTERSET utf8
infile 'df_1.txt'
append
into table SZ_METRO_HIS_DEAL
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
'CARD_ID',
 'CARD_TYPE',
 'TRADE_TYPE',
 'TRADE_ADDRESS',
 'TRADE_DATE' DATE 'YYYY/MM/DD HH24:MI:SS',
 'TERMINAL_ID',
 'TRADE_MONEY',
 'TRADE_VALUE',
 'CURRENT_VALUE',
 'RECV_TIME',
 'DESTINATION'        
)

