

create table SZ_METRO_HIS_DEAL(
CARD_ID NUMBER(16),
CARD_TYPE NUMBER(2),
CURRENT_VALUE NUMBER(12),
DESTINATION NUMBER(14,2),
RECV_TIME VARCHAR(18),
TERMINAL_ID NUMBER(9),
TRADE_ADDRESS NUMBER(10),
TRADE_DATE DATE ,
TRADE_MONEY NUMBER(5),
TRADE_TYPE NUMBER(3),
TRADE_VALUE VARCHAR(16)
);

create table SZ_TRADE_TYPE(
TRADE_TYPE CHAR(2),
CONTENT VARCHAR(20),
CLASS1 VARCHAR(20)
);

create table SZ_CARD_TYPE(
CARD_TYPE CHAR(2),
CARD_NAME varchar(30)
);

create table SZ_TAD_LINE_STATION(
LINE_ID CHAR(6),
STATION_NAME VARCHAR(20),
OPERATION_ID VARCHAR(20),
STATION_ID VARCHAR(10),
LINE_NAME VARCHAR(12)
);

#notes
1 票卡类型对照表，有没有更详细说明，例如CARD_TYPE为66，68都表示深圳通储值票，具体的区别？是不是还有票卡子类型来区别票卡？
2 交易类型对照表，交易类型TRADE_TYPE 01表示售卡具体是值什么，和后面的交易类型21（进站），22（出站）有没有关系，例如是不是售卡后也会有进站、出站记录？

create table SZ_METRO_HIS_DEAL_INDEXES(
ID NUMBER(12) primary key,
CARD_ID NUMBER(16),
TRADE_TYPE NUMBER(3),
CARD_TYPE NUMBER(2),
TRADE_ADDRESS NUMBER(10),
TERMINAL_ID NUMBER(9),
TRADE_MONEY NUMBER(5),
TRADE_VALUE VARCHAR(16),
CURRENT_VALUE NUMBER(12),
TRADE_DATE DATE ,
DESTINATION NUMBER(14,2),
RECV_TIME VARCHAR(20)
);
