LOAD DATA 
CHARACTERSET UTF8
INFILE 'in_10w.txt'
INSERT
INTO TABLE tai_entry_his
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
  (
	BALANCE_WATER_NO, 
	CARD_MAIN_CODE, 
	CARD_STATUS_ID, 
	CARD_SUB_CODE, 
	DEVICE_ID, 
	DEVICE_TYPE_ID, 
	IN_TIME  DATE "YYYY-MM-DD HH24:MI:SS" terminated by ".000000,",
	LINE_ID, 
	SAM_LOGICAL_ID, 
	SAM_TR_SEQ, 
	STATION_ID, 
	TK_BALANCE, 
	TK_LOGIC_NO, 
	TK_PHY_NO, 
	SQUAD_DATE, 
	TIME_SECTION, 
	ID, 
	COUNTER_TIME, 
	BUS_TIMES_COUNTER, 
	METRO_TIMES_COUNTER, 
	UNION_TIMES_COUNTER, 
	TK_CHARGE_CNT, 
	TK_DEAL_CNT, 
	TAC, 
	PAYMODE_ID, 
	LAST_SAM_LOGICAL_ID, 
	LAST_DEAL_TIME, 
	TR_SORT, 
	AREA_CODE, 
	AREA_TK_TYPE, 
	OVERDRAFT, 
	CPU_TK, 
	EXPIRED_TK, 
	TCT_VALID_DAYS, 
	TCT_ACTIVATE_TIME  DATE "YYYY-MM-DD HH24:MI:SS" terminated by ".000000,", 
	LIMIT_MODE, 
	LIMIT_ENTRY_STATION, 
	LIMIT_EXIT_STATION, 
	DATA_FILE_NAME, 
	FILE_NAME
   )
